version: "3.9"

services:
  api:
    build:
      context: .
    image: ageht/skypro_hw_26
    ports:
      - 80:80
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    image: ageht/skypro_hw_26
    command: flask db upgrade
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: Pv3tDf18
      POSTGRES_DB: flask_app
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5